// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtE3cSz92ORBUoaFVLtuI5J2BXGwAwbss',
    appId: '1:629791623604:web:1dfbb9a2058ac7e4514ae1',
    messagingSenderId: '629791623604',
    projectId: 'assignment2-appdev-9fd62',
    authDomain: 'assignment2-appdev-9fd62.firebaseapp.com',
    storageBucket: 'assignment2-appdev-9fd62.appspot.com',
    measurementId: 'G-6G378Z4YHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJfWxY0Rl2rSFcaQeoSjIR7Dmr64ldEIA',
    appId: '1:629791623604:android:3ba3556e2dbc2230514ae1',
    messagingSenderId: '629791623604',
    projectId: 'assignment2-appdev-9fd62',
    storageBucket: 'assignment2-appdev-9fd62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs2lEKO0xeUpe3Ts8uV8yb41xnjrdXp6I',
    appId: '1:629791623604:ios:c835914bba930d41514ae1',
    messagingSenderId: '629791623604',
    projectId: 'assignment2-appdev-9fd62',
    storageBucket: 'assignment2-appdev-9fd62.appspot.com',
    iosBundleId: 'com.example.assignment2Appdev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs2lEKO0xeUpe3Ts8uV8yb41xnjrdXp6I',
    appId: '1:629791623604:ios:c835914bba930d41514ae1',
    messagingSenderId: '629791623604',
    projectId: 'assignment2-appdev-9fd62',
    storageBucket: 'assignment2-appdev-9fd62.appspot.com',
    iosBundleId: 'com.example.assignment2Appdev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtE3cSz92ORBUoaFVLtuI5J2BXGwAwbss',
    appId: '1:629791623604:web:0cbdd4492f6f9631514ae1',
    messagingSenderId: '629791623604',
    projectId: 'assignment2-appdev-9fd62',
    authDomain: 'assignment2-appdev-9fd62.firebaseapp.com',
    storageBucket: 'assignment2-appdev-9fd62.appspot.com',
    measurementId: 'G-WBC695CL7N',
  );
}
